name: CI

on:
  merge_group:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install apt dependencies
      run: sudo apt update && sudo apt install -y libcairo2-dev libgirepository1.0-dev
    - name: Install dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: requirements.txt
    - name: Run mypy
      run: mypy
